name: Prettier Format Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install prettier

      - name: Check formatting with Prettier
        run: |
          echo "Checking code formatting with Prettier..."
          # Run prettier in check mode to verify formatting without changing files
          # The command will exit with error code if any files need formatting
          npx prettier --config .prettierrc --check "**/*.{js,jsx,ts,tsx,json,css,scss,md}"

      - name: Provide instructions if check fails
        if: ${{ failure() }}
        run: |
          echo "::error::❌ Prettier check failed! Some files are not properly formatted."
          echo "::error::Please run 'npm run format' locally to fix formatting issues before pushing again."
          exit 1
